rails-app/goozs/gooz/config/routes.rb
Rails.application.routes.draw do
  resources :goozs
  get 'welcome/index'

  resources :gooz

  root 'welcome#index'
end

rails-app/goozs/gooz/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails-app/goozs/gooz/app/models/gooz.rb
class Gooz < ApplicationRecord
        def goozvalue=(string)
                # do my vault stuff
                secret = Vault.logical.write("transit/encrypt/goozs", plaintext: Base64.strict_encode64(string))
                enc_value = secret.data[:ciphertext]
                super(enc_value)
        end
        def decryptedvalue
                secret = Vault.logical.write("transit/decrypt/goozs", ciphertext: goozvalue)
                dec_value = Base64.strict_decode64 secret.data[:plaintext]
        end
end

rails-app/goozs/gooz/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rails-app/goozs/gooz/app/controllers/gooz_controller.rb
class GoozController < ApplicationController
        def new
                @gooz=
        end
end

rails-app/goozs/gooz/app/controllers/goozs_controller.rb
class GoozsController < ApplicationController
  before_action :set_gooz, only: [:show, :edit, :update, :destroy]

  # GET /goozs
  # GET /goozs.json
  def index
    @goozs = Gooz.all
  end

  # GET /goozs/1
  # GET /goozs/1.json
  def show
  end

  # GET /goozs/new
  def new
    @gooz = Gooz.new
  end

  # GET /goozs/1/edit
  def edit
  end

  # POST /goozs
  # POST /goozs.json
  def create
    @gooz = Gooz.new(gooz_params)

    respond_to do |format|
      if @gooz.save
        format.html { redirect_to @gooz, notice: 'Gooz was successfully created.' }
        format.json { render :show, status: :created, location: @gooz }
      else
        format.html { render :new }
        format.json { render json: @gooz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goozs/1
  # PATCH/PUT /goozs/1.json
  def update
    respond_to do |format|
      if @gooz.update(gooz_params)
        format.html { redirect_to @gooz, notice: 'Gooz was successfully updated.' }
        format.json { render :show, status: :ok, location: @gooz }
      else
        format.html { render :edit }
        format.json { render json: @gooz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goozs/1
  # DELETE /goozs/1.json
  def destroy
    @gooz.destroy
    respond_to do |format|
      format.html { redirect_to goozs_url, notice: 'Gooz was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gooz
      @gooz = Gooz.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gooz_params
      params.require(:gooz).permit(:goozname, :goozvalue)
    end
end

rails-app/goozs/gooz/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

rails-app/goozs/gooz/app/helpers/application_helper.rb
module ApplicationHelper
end

rails-app/goozs/gooz/app/helpers/gooz_helper.rb
module GoozHelper
end

rails-app/goozs/gooz/app/helpers/goozs_helper.rb
module GoozsHelper
end

rails-app/goozs/gooz/app/helpers/welcome_helper.rb
module WelcomeHelper
end

rails-app/goozs/gooz/app/views/gooz/new.html.erb
<h1>New Gooz</h1>
<%= form_for @gooz do |form| %>
  <p>
    <%= form.label :goozname %><br>
    <%= form.text_field :goozname %>
  </p>

  <p>
    <%= form.label :goozvalue %><br>
    <%= form.text_field :goozvalue %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

rails-app/goozs/gooz/app/views/goozs/_form.html.erb
<%= form_for(gooz) do |f| %>
  <% if gooz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gooz.errors.count, "error") %> prohibited this gooz from being saved:</h2>

      <ul>
      <% gooz.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :goozname %>
    <%= f.text_field :goozname %>
  </div>

  <div class="field">
    <%= f.label :goozvalue %>
    <%= f.text_field :goozvalue %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails-app/goozs/gooz/app/views/goozs/edit.html.erb
<h1>Editing Gooz</h1>

<%= render 'form', gooz: @gooz %>

<%= link_to 'Show', @gooz %> |
<%= link_to 'Back', goozs_path %>

rails-app/goozs/gooz/app/views/goozs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Goozs</h1>

<table>
  <thead>
    <tr>
      <th>Goozname</th>
      <th>Goozvalue</th>
      <th>Goozdecrypted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goozs.each do |gooz| %>
      <tr>
        <td><%= gooz.goozname %></td>
        <td><%= gooz.goozvalue %></td>
        <td><%= gooz.decryptedvalue %></td>
        <td><%= link_to 'Show', gooz %></td>
        <td><%= link_to 'Edit', edit_gooz_path(gooz) %></td>
        <td><%= link_to 'Destroy', gooz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gooz', new_gooz_path %>

rails-app/goozs/gooz/app/views/goozs/new.html.erb
<h1>New Gooz</h1>

<%= render 'form', gooz: @gooz %>

<%= link_to 'Back', goozs_path %>

rails-app/goozs/gooz/app/views/goozs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Goozname:</strong>
  <%= @gooz.goozname %>
</p>

<p>
  <strong>Goozvalue:</strong>
  <%= @gooz.goozvalue %>
</p>

<%= link_to 'Edit', edit_gooz_path(@gooz) %> |
<%= link_to 'Back', goozs_path %>

rails-app/goozs/gooz/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails-app/goozs/gooz/app/views/welcome/index.html.erb
<h1>Vault Test</h1>
<p><a href="goozs">goozs</a></p>